version: '3.7'

services:
  mysql-counterstrike:
    image: mysql:latest
    ports:
      - '3307:3306'
    restart: always
    environment:
      MYSQL_DATABASE: counterstrike_db
      #      MYSQL_USER: root
      #      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-counterstrike-data:/var/lib/mysql

volumes:
  mysql-counterstrike-data: